#pragma config(Sensor, S1,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main
{
	// initialise variables
	int counter = 0;
	int white_box = 0;
	int black_box = 0;

	while(1 == 1)
	{
		// drive straight
		motor[motorC] = 25;
		motor[motorB] = 25;

		// while loop for detecting white light
		while(SensorValue(lightSensor) <= 65)
		{
			motor[motorC] = 50;
			motor[motorB] = 50;
		} // end while

		sleep(250);

		if(SensorValue(lightSensor) <= 65)
		{
			black_box ++;
		} // end if
		else
		{white_box ++;
		} // end else

		// increment counter
		counter ++;

		displayTextLine(1, "%d lines", counter);
		displayTextLine(2, "%d white boxes", white_box);
		displayTextLine(3, "%d black boxes", black_box);

		// while loop for whilst there is black light
		while(SensorValue(lightSensor) >= 45)
		{
			motor[motorC] = 50;
			motor[motorB] = 50;
		} // end while

	} // end while

} // end main
