#pragma config(Sensor, S1,     bumper,         sensorEV3_Touch)
#pragma config(Sensor, S3,     lightSensor,    sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors lightSensor = (tSensors) S3;
const tSensors sonarSensor = (tSensors) S1;

task main()
{
	while(SensorValue(bumper) == 0)
	{
		while(SensorValue(lightSensor)< 30)
	  {
	  	motor[motorC]=50;
	  	motor[motorB]=0;
	  }
	  while(SensorValue(lightSensor) >= 30)
	  {
	  	motor[motorC] = 0;
	  	motor[motorB] = 50;
		}
   }

}
