#pragma config(Sensor, S3,     lightSensor,    sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors lightSensor = (tSensors) S3;

task main()
{
	while(1==1)
	{
		while(SensorValue(lightSensor)< 30)
	  {
	  	motor[motorC]=30;
	  	motor[motorB]=0;
	  }
	  while(SensorValue(lightSensor) >= 30)
	  {
	  	motor[motorC] = 0;
	  	motor[motorB] = 30;
		}
   }
}
