#pragma config(Sensor, S1,     bumper,         sensorEV3_Touch)
#pragma config(Sensor, S4,     ultrasonic,     sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(SensorValue(bumper) == 0)
 {
	 motor[motorC] = 50;
	 motor[motorB] = 50;

 }
 motor[motorC] = 0;
 motor[motorB] = -35;
 wait1Msec(1000);

 while(SensorValue(ultrasonic) > 25)
 {
 	motor[motorC] = 50;
 	motor[motorB] = 50;
 }

 motor[motorC] = 0;
 motor[motorB] = -35;
 wait1Msec(1000);

 while(SensorValue(ultrasonic) > 10)
 {
 	motor[motorC] = 50;
 	motor[motorB] = 50;
 }

 motor[motorC] = 0;
 motor[motorB] = -35;
 wait1Msec(1000);


}
