#pragma config(Sensor, S3,     Lightsensor,    sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(SensorValue(Lightsensor)>15)
 {

 		motor[motorC] = 50;
 		motor[motorB] = 50;
 }

 	motor[motorC] = -50;
 	motor[motorB] = -50;
 	wait1Msec(1000);

}
