#pragma config(Sensor, S3,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// initialise variables
	int counter = 0;

	while(1 == 1)
	{
		// drive straight
		motor[motorC] = 50;
		motor[motorB] = 50;

		// while loop for detecting white light
		while(SensorValue(lightSensor) <= 65)
		{
			motor[motorC] = 50;
			motor[motorB] = 50;

			displayCenteredBigTextLine(3, "%d", counter);
		} // end while

		// increment counter
		counter ++;

		// while loop for whilst there is black light
		while(SensorValue(lightSensor) >= 45)
		{
			motor[motorC] = 50;
			motor[motorB] = 50;
			displayCenteredBigTextLine(3, "%d", counter);
		} // end while

	} // end while

} // end main
