#pragma config(Sensor, S3,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//sensor slot
const tSensors lightSensor = (tSensors) S3;
const tSensors ultrasonic = (tSensors) S4;


task main()
{
	nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
	while(1==1)
	{
		while(SensorValue(lightSensor)< 30)//detects less than 30
	  {
	  	motor[motorC]=30;
	  	motor[motorB]=0;
	  }
	  while(SensorValue(lightSensor) >= 30)
	  {
	  	motor[motorC] = 0;
	  	motor[motorB] = 30;
		}
		if(SensorValue(sonarSensor)<30) //sonarsensor less than 25 turn
		{
			motor[motorC]=20;
	  	motor[motorB]=40;
	  	wait1Msec(2500);

			motor[motorC]=40
	  	motor[motorB]=20
	  	wait1Msec(2500);

	  }
   }
}
