#pragma config(Sensor, S1,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//motorc = right motor

task main
{
	// initialise variables
	int counter = 0;
	int white_box = 0;
	int black_box = 0;
	int grid[7] [10];



	//setting up counting position from start
	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(1825);

	motor[motorC] = -25;
	motor[motorB] = 25;
	wait1Msec(750);

	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(5725);

	motor[motorC] = -25;
	motor[motorB] = 25;
	wait1Msec(750);




	//counting boxes
	while(counter < 71)
	{
		if(counter % 7 != 0 || counter < 8)
		{
			// drive straight
			motor[motorC] = 50;
			motor[motorB] = 50;

			// while loop for detecting white light
			while(SensorValue(lightSensor) <= 65)
			{
				motor[motorC] = 50;
				motor[motorB] = 50;
			} // end while

			sleep(250);

			if(SensorValue(lightSensor) <= 65)
			{
				black_box ++;
			} // end if
			else
			{
				white_box ++;
			} // end else

			// increment counter
			counter ++;

			displayTextLine(1, "%d lines", counter);
			displayTextLine(2, "%d white boxes", white_box);
			displayTextLine(3, "%d black boxes", black_box);

			// while loop for whilst there is black light
			while(SensorValue(lightSensor) >= 45)
			{
				motor[motorC] = 50;
				motor[motorB] = 50;
			} // end while}
		} // end if
		else
		{
			motor[motorC] = -25;
			motor[motorB] = 25;
			wait1Msec(750);

			motor[motorC] = 50;
			motor[motorB] = 50;
			wait1Msec(2500);

			motor[motorC] = -25;
			motor[motorB] = 25;
			wait1Msec(750);
		} // end else
	} // end while


} // end main
