#pragma config(Sensor, S1,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//NOTE: motorB is left motor, motorC is right motor

//macro definitions
#define SIZE 70

task main
{
	//initialisation of variables
	int counter = 0;
	int white_box = 0;
	int black_box = 0;
	int turn_count = 0;
	int i, j;
	int grid[7] [10] = {
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 2, 0, 0, 0}
		};

	//moving robot from starting position to counting position
	//making robot drive straight for 1.825 seconds
	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(1825);

	//making robot turn left for .75 seconds
	motor[motorC] = -25;
	motor[motorB] = 25;
	wait1Msec(750);

	//making robot drive straight for 5.725 seconds
	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(5725);

	//making robo turn left for .75 seconds
	motor[motorC] = -25;
	motor[motorB] = 25;
	wait1Msec(750);

	//while loop for detecting an object
	while(SensorValue(sonarSensor)<30)
	{
		//for loop 1 for counting boxes
		for(i=0; i < SIZE; i++)
		{
			//for loop 2 for counting boxes
			for(j=0; j < SIZE; j++)
			{
				//counting boxes
				while(counter < 71)
				{
					//if statement for making robot turn at the end of each row
					if(counter % 7 != 0 || counter < 8)
					{
						//making robot drive straight
						motor[motorC] = 50;
						motor[motorB] = 50;

						//while loop for detecting white light
						while(SensorValue(lightSensor) <= 65)
						{
							motor[motorC] = 50;
							motor[motorB] = 50;
						}//end while

						//making robot wait .25 seconds before checking colour of box
						sleep(250);

						//if statement for checking colour of box
						if(SensorValue(lightSensor) <= 65)
						{
							black_box ++;
						}//end if
						else
						{
							white_box ++;
						}//end else

						//increment counter
						counter ++;

						//displaying amount of boxes and white/black boxes
						displayTextLine(1, "%d lines", counter);
						displayTextLine(2, "%d white boxes", white_box);
						displayTextLine(3, "%d black boxes", black_box);

						//while loop for whilst there is black light
						while(SensorValue(lightSensor) >= 45)
						{
							motor[motorC] = 50;
							motor[motorB] = 50;
						}//end while
					}//end if
					//else statement for if robot reaches end of row
					else
					{
						//if statement for telling robot to turn left
						if(turn_count % 2 == 1)
						{
							//making robot turn left for .75 seconds
							motor[motorC] = -25;
							motor[motorB] = 25;
							wait1Msec(750);

							//making robot drive straight for 2.5 seconds
							motor[motorC] = 50;
							motor[motorB] = 50;
							wait1Msec(2500);

							//making robot turn left for .75 seconds
							motor[motorC] = -25;
							motor[motorB] = 25;
							wait1Msec(750);
						}//end if
						else
						{
							//making robot turn right for .75
							motor[motorC] = 25;
							motor[motorB] = -25;
							wait1Msec(750);

							//making robot drive straight for 2.5 seconds
							motor[motorC] = 50;
							motor[motorB] = 50;
							wait1Msec(2500);

							//making robot turn right for .75 seconds
							motor[motorC] = 25;
							motor[motorB] = -25;
							wait1Msec(750);
						}//end else
					}//end else
				}//end while
			}//end for
		}//end for
	}//end while
}//end main
