#pragma config(Sensor, S3,     Lightsensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     ultrasonic,     sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors ultrasonic = (tSensors) S4;
//*!!CLICK to edit ‘wizard’ created sensor
task main()
{
 while(1==1)
 {
 	motor[motorC] = 50;
 	motor[motorB] = 50;
 }

 motor[motorC] = -50;
 motor[motorB] = -50;
 wait1Msec(1000);

}
