#pragma config(Sensor, S1,     bumper,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors sonarSensor = (tSensors) S1;
//*!!CLICK to edit ‘wizard’ created sensor
task main()
{
 while(SensorValue(bumper) == 0)
 {
	 motor[motorC] = 50;
	 motor[motorB] = 50;

 }
 motor[motorC] = -50;
 motor[motorB] = -50;
 wait1Msec(1000);

}
